### ISSUE TITLE
House (First Level) Benchmark Task list

### ISSUE THREAD

**Issue by sonkiboy** [sonkiboy/Feywood#13]
- [ ] Camera Tracks
- [ ] Wall transition shader
- [ ]  Climbing
- [ ] dialogue interaction w/ npc
- [ ] UI design for dialogue and button input
